### ISSUE TITLE
关于跨域实验

### ISSUE THREAD

**Issue by fly-dk** [BNU-IVC/FastPoseGait#10]
你好，我在CASIA-B上进行了gpgait的训练和测试，但是如何利用训练出的模型对OUMVLP进行测试？（已经对OUMVLP进行了处理

**Comment by DreamShibei** [comment]
You can modify these three lines to facilitate the cross-domain evaluation.
[config](https://github.com/BNU-IVC/FastPoseGait/blob/8140f6714f2f47cb6a2d90afcdb777b8c6fd5857/configs/gpgait/gpgait.yaml#L3C3-L5C29)
