### ISSUE TITLE
关于CASIA-B数据集逐帧对应的疑问

### ISSUE THREAD

**Issue by liguge** [BNU-IVC/FastPoseGait#12]
我在跑一个多模态的代码。论文的题目是A Multi-Stage Adaptive Feature Fusion Neural Network for Multimodal Gait Recognition（10.1109/TBIOM.2024.3384704），我的疑问涉及论文的预处理部分，就是拼合剪影图数据和骨骼点数据。我下载了原始的CASIA-B数据集和您提供的CASIA-B-pose数据集。但是在合并数据集的时候，
![image](https://github.com/BNU-IVC/FastPoseGait/assets/19371493/88a81308-2b2d-4134-bca1-d6ae76b3d7e4)
![image](https://github.com/BNU-IVC/FastPoseGait/assets/19371493/b210bfe3-c457-4ba5-9aff-76ce170966e1)
这样的话就导致数据集报错了，报错的原因是：89和98不对应，我下载的原始数据集的里面有89张图片，但是您给的数据集的原始数据里面有98张图片。我猜测是您下载的原始数据集的图片更多。001\bg-01\000，

我下载的图片数据集的示意图：
![image](https://github.com/BNU-IVC/FastPoseGait/assets/19371493/e775cf32-f871-45da-9ace-843b3c1f6d3d)
不知道能否分享一下您的原始数据的剪影图的图片呢？我是一个小白，还不知道怎么处理这种情况。使得图片的帧数变得一致。请问有什么思路可以提供吗？

**Comment by liguge** [comment]
**或者说我目前想要自己跑骨骼点数据，请问有什么资料可以提供吗？因为目前给的剪影图和pose数据确实不对应。**

> 我在跑一个多模态的代码。论文的题目是A Multi-Stage Adaptive Feature Fusion Neural Network for Multimodal Gait Recognition（10.1109/TBIOM.2024.3384704），我的疑问涉及论文的预处理部分，就是拼合剪影图数据和骨骼点数据。我下载了原始的CASIA-B数据集和您提供的CASIA-B-pose数据集。但是在合并数据集的时候， ![image](https://private-user-images.githubusercontent.com/19371493/342007640-88a81308-2b2d-4134-bca1-d6ae76b3d7e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMDgwMDcsIm5iZiI6MTcxOTEwNzcwNywicGF0aCI6Ii8xOTM3MTQ5My8zNDIwMDc2NDAtODhhODEzMDgtMmIyZC00MTM0LWJjYTEtZDZhZTc2YjNkN2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDAxNTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZDU5NWUxZmY5YjE4M2MxYTA5MzgwM2ZlYjE2OTIxOWMzYzlmMDM5YWQwMzliNWVhY2Y4ZTBkMmQ4ZmEzOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G6eno6UolT9Hq-ih5hiZBcgN3TY15aubf2dnNELGH6g) ![image](https://private-user-images.githubusercontent.com/19371493/342007643-b210bfe3-c457-4ba5-9aff-76ce170966e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMDgwMDcsIm5iZiI6MTcxOTEwNzcwNywicGF0aCI6Ii8xOTM3MTQ5My8zNDIwMDc2NDMtYjIxMGJmZTMtYzQ1Ny00YmE1LTlhZmYtNzZjZTE3MDk2NmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDAxNTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzY2M3NjhiNmEyMTBjY2I1Mzc4NmJkZmU0NTNlYzgwYTk5MmRhZWFlZWVlN2ViOWM4ZDM3MDkyMmNkMmE4M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z_Azl3-V-Ljzss3oDLGin5VRVAg6YQV-57csX7Scblw) 这样的话就导致数据集报错了，报错的原因是：89和98不对应，我下载的原始数据集的里面有89张图片，但是您给的数据集的原始数据里面有98张图片。我猜测是您下载的原始数据集的图片更多。001\bg-01\000，
> 
> 我下载的图片数据集的示意图： ![image](https://private-user-images.githubusercontent.com/19371493/342007647-e775cf32-f871-45da-9ace-843b3c1f6d3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMDgwMDcsIm5iZiI6MTcxOTEwNzcwNywicGF0aCI6Ii8xOTM3MTQ5My8zNDIwMDc2NDctZTc3NWNmMzItZjg3MS00NWRhLTlhY2UtODQzYjNjMWY2ZDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDAxNTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMmE4NzkyZTFhNjU4MWU3NTM4NmY2OTE1ZGQ3MzlhN2RhNjI5NDE0ZjE2OWMwMzYzNGVlODcyNWM4MTgzOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uQlnNOrJoro9jj9CUYQyAA7qa-vg55EfDf0ONFrTIrQ) 不知道能否分享一下您的原始数据的剪影图的图片呢？我是一个小白，还不知道怎么处理这种情况。使得图片的帧数变得一致。请问有什么思路可以提供吗？

**Comment by DreamShibei** [comment]
Hello! Currently, the officially open-sourced silhouette data also corresponds one-to-one with RGB data. If you need to perform frame-level alignment, you can select frames where both pose and silhouette data are present.
