### ISSUE TITLE
你好，对于GPGait, 如果想把关节和骨骼数量变一变，应该怎么修改角度列表呢？

### ISSUE THREAD

**Issue by heyihao2018** [BNU-IVC/FastPoseGait#13]
![屏幕截图 2024-09-04 162457](https://github.com/user-attachments/assets/ffdee184-075a-4a31-ba71-6ddcd37676b6)

**Comment by DreamShibei** [comment]
你好，如果改变关节和骨骼数量，需要修改[HOD的计算方式](https://github.com/BNU-IVC/FastPoseGait/blob/8140f6714f2f47cb6a2d90afcdb777b8c6fd5857/fastposegait/data/transform.py#L228C7-L228C21)，[Graph的构建](https://github.com/BNU-IVC/FastPoseGait/blob/8140f6714f2f47cb6a2d90afcdb777b8c6fd5857/fastposegait/modeling/graph/graph.py#L3)以及[关键点最终分part的划分方式](https://github.com/BNU-IVC/FastPoseGait/blob/8140f6714f2f47cb6a2d90afcdb777b8c6fd5857/fastposegait/modeling/graph/partition.py#L4)
