### ISSUE TITLE
torch.distributed.launch分布式训练只有一个gpu怎么解决

### ISSUE THREAD

**Issue by carrot-wuziyu** [BNU-IVC/FastPoseGait#14]
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set
电脑只有一个gpu，跑不通应该怎么解决

**Comment by DreamShibei** [comment]
你好，可以把脚本中的启动命令设置为：CUDA_VISIBLE_DEVICES=0，--nproc_per_node=1
