### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by asafjo23** [BNU-IVC/FastPoseGait#15]
Hi :-)

I tried to locate [GaitTR](https://arxiv.org/abs/2204.03873) and [GPGait](https://arxiv.org/abs/2303.05234) weights under the model zoo but it seems they are missing. Is there any way to get them please?

**Comment by aleeyang** [comment]
Hi, please try  [this](https://drive.google.com/drive/folders/1jsQ5cZcZ5YXVvzSvyEETlN6l1B7T6paD?usp=drive_link).
The download link in README has been already updated, please check it~

**Comment by asafjo23** [comment]
Thanks!
