### ISSUE TITLE
Pretreatment of SUSTech1K and CCPG 

### ISSUE THREAD

**Issue by SoliveTech** [BNU-IVC/FastPoseGait#16]
Thank you for your outstanding work！
I am very interested in SUSTech1K and CCPG, can you give the processing code that can adapt to gpgait model ?

**Comment by DreamShibei** [comment]
Hi! The officially open-sourced poses from [SUSTech1K](https://lidargait.github.io/) and [CCPG](https://github.com/BNU-IVC/CCPG) can be directly utilized in our project

**Comment by DreamShibei** [comment]
Hi! The officially open-sourced poses from [SUSTech1K](https://lidargait.github.io/) and [CCPG](https://github.com/BNU-IVC/CCPG) can be directly utilized in our project and they do not need pre-processing.

**Comment by SoliveTech** [comment]
Because the directory Settings don't quite match the model, these two datasets don't seem to work directly. In addition, CCPG does not have 2d skeleton data. It said in the model zoo provided by the doc that hrnet was used for extraction on CCGP. I wonder if you are willing to provide the data you extracted : )

**Comment by DreamShibei** [comment]
The directory settings of SUSTech1K can be seen in [this link](https://github.com/ShiqiYu/OpenGait/tree/master/datasets/SUSTech1K). You can directly use it by adding one line in data_cfg:
`data_in_use: [false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false]`. The pose of CCPG is updated in [this repo](https://github.com/BNU-IVC/CCPG) and you can apply for it after submitting the corresponding agreement.
