### ISSUE TITLE
Questions about the paper and implementation

### ISSUE THREAD

**Issue by z915287285** [BNU-IVC/FastPoseGait#6]
Hello, I have some questions after reading your paper and hope to get your answers.
1.Temporal correlation verification. Have you considered doing some verification of the time contribution of the TCN module?
2.About Oumvlp Dataset. The Oumvlp dataset exists in the verification part of the reference code. Are there any experimental results of Oumvlp-pose?

**Comment by DreamShibei** [comment]
Hi! Thanks for your interest. 
1. Considering the set-based method is more robust to the condition of discontinuous frames or different frame rates, which is more applicable in real-world scenarios, we finally choose not to use the TCN module in our work.
2. OUMVLP-Pose is extracted from RGB frames of the OUMVLP dataset. We have reported the results of OUMVLP-Pose both in [GPGait](https://arxiv.org/abs/2303.05234) and [FastPoseGait](https://arxiv.org/abs/2309.00794).

**Comment by z915287285** [comment]
Thank you for your answer！
