### ISSUE TITLE
the meaning of self.flip_idx and connect_joint in graph.py

### ISSUE THREAD

**Issue by Hotels9Lee** [BNU-IVC/FastPoseGait#8]
Could you please explain what self.flip_idx and connect_joint in graph.py mean? Or what human joint information they represent

**Comment by DreamShibei** [comment]
Hi, `self.flip_idx`  refers to the symmetrical keypoint id of each joint, which can be used in data argumentations or other model designs. 
`connect_joint` is to define the connected keypoint of each joint and `len(connect_joint)` is the number of keypoints, this is used in GaitGraph2 to calculate the multi-input.
