### ISSUE TITLE
Alignment or Normalization of 2D Skeletons

### ISSUE THREAD

**Issue by ZziTaiLeo** [BNU-IVC/FastPoseGait#9]
Thank you for your outstanding work!  Based on your extensive experience in this area, I would like to ask if there is almost no work on aligning the root nodes of the skeleton or further normalizing them.

**Comment by DreamShibei** [comment]
Good question and thanks for your interest!
There exists some work trying to normalize 2D skeletons in pose-based gait recognition but not as comprehensive as ours. You can refer to our paper [GPGait](https://openaccess.thecvf.com/content/ICCV2023/papers/Fu_GPGait_Generalized_Pose-based_Gait_Recognition_ICCV_2023_paper.pdf) in Table 2 for more details.
